name: Build & Publish to Dynamis Latest

on:
  release:
    types: [released]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download Dalamud Latest
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore Project
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release MBT/MBT.csproj -p:AssemblyVersion=${{ github.ref_name }}

      - name: Publish Version
        uses: PunishXIV/dynamis-action@v1
        id: dynamis
        with:
          plugin_id: 59
          internal_name: "MBT"
          version_number: ${{ github.ref_name }}
          path: "MBT/bin/Release/MBT/latest.zip"
          type: "latest"
          dalamud_version: "10"
          changelog: ${{ github.event.release.body }}
        env:
          PUBLISHER_KEY: ${{ secrets.PUBLISHER_KEY }}
